title: Perdana Hadi Sanjaya
description: >
 Full Snack Backend Engineer / SysAdmin / DevOps / FOSS Enthusiast
copyright: Ok
sass:
  sass_dir: assets/sass
baseurl: ""
url: "https://www.perdanahadisanjaya.cf/"
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "ceroberoz"
feed_icon: rss
email: "perdanahadisanjaya@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
